### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by jj89757hhb** [bawn/RAC-Demo#2]
rac 这种写法确实有牛逼的地方
但是感觉代码复杂度会增加很多！
您是怎么接受这种写法的呢？

**Comment by bawn** [comment]
其实不是增加了代码的复杂度，而是函数式的概念在 Objective-C 并不是很常见，所以会觉得复杂。关于接受，我也只是去尝试不同的开发模式，比如用 ReactiveCocoa 可以比较方便的去实现 MVVM 模式。

另外我不是很建议把 ReactiveCocoa（尤其是 Objective-C 版 ReactiveCocoa ，因为ReactiveCocoa已经全面转向了 swif了） 用在商业项目上，除非你们的团队都已经熟悉函数式的编程模式

**Comment by jj89757hhb** [comment]
恩  这种写法需要时间的适应
